name: binance_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  convert: ^3.0.0
  http: ^0.13.0
  crypto: ^3.0.0
  web_socket_channel: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
